using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using Dapper;
using EasyDapper.Attributes;

namespace EasyDapper
{
    /// <summary>
    /// Implements bulk insert operations on top of <see cref="SqlBulkCopy"/>. Two strategies are
    /// supported:
    /// <list type="bullet">
    /// <item><description>Direct bulk copy (default) — fastest, but the caller cannot retrieve
    /// any identity values generated by the database.</description></item>
    /// <item><description>Bulk copy via a temp table with an order column, followed by an
    /// INSERT...OUTPUT that retrieves generated identities in the original order. Selected with
    /// <c>generateIdentities: true</c>.</description></item>
    /// </list>
    /// </summary>
    internal class BulkOperations
    {
        private readonly ConnectionManager _connectionManager;
        private readonly QueryCache _queryCache;
        private readonly SqlBuilder _sqlBuilder;
        private const int DEFAULT_BATCH_SIZE = 100;

        public BulkOperations(ConnectionManager connectionManager, QueryCache queryCache, SqlBuilder sqlBuilder)
        {
            if (connectionManager == null) throw new ArgumentNullException("connectionManager");
            if (queryCache == null) throw new ArgumentNullException("queryCache");
            if (sqlBuilder == null) throw new ArgumentNullException("sqlBuilder");
            _connectionManager = connectionManager;
            _queryCache = queryCache;
            _sqlBuilder = sqlBuilder;
        }

        public int InsertList<T>(IEnumerable<T> entities, bool generateIdentities = false) where T : class
        {
            if (entities == null) throw new ArgumentNullException("entities");
            var entityList = entities as IList<T> ?? entities.ToList();
            if (entityList.Count == 0) return 0;
            var identityProp = _queryCache.GetIdentityProperty<T>();
            if (identityProp != null && generateIdentities) return InsertListWithIdentity(entityList);
            InsertBulkCopy(entityList);
            return entityList.Count;
        }

        public async Task<int> InsertListAsync<T>(IEnumerable<T> entities, bool generateIdentities = false, CancellationToken cancellationToken = default) where T : class
        {
            if (entities == null) throw new ArgumentNullException("entities");
            var entityList = entities as IList<T> ?? entities.ToList();
            if (entityList.Count == 0) return 0;
            var identityProp = _queryCache.GetIdentityProperty<T>();
            if (identityProp != null && generateIdentities)
                return await InsertListWithIdentityAsync(entityList, cancellationToken).ConfigureAwait(false);
            await InsertBulkCopyAsync(entityList, cancellationToken).ConfigureAwait(false);
            return entityList.Count;
        }

        private void InsertBulkCopy<T>(IEnumerable<T> entities) where T : class
        {
            var tableName = _queryCache.GetTableName<T>();
            var properties = GetInsertProperties<T>();
            var dataTable = _sqlBuilder.ToDataTable(entities, properties);
            var connection = (SqlConnection)_connectionManager.GetOpenConnection();
            var transaction = (SqlTransaction)_connectionManager.CurrentTransaction;
            using (var reader = dataTable.CreateDataReader())
            using (var bulkCopy = new SqlBulkCopy(connection, SqlBulkCopyOptions.Default, transaction))
            {
                ConfigureBulkCopy<T>(bulkCopy, dataTable, properties);
                bulkCopy.WriteToServer(reader);
            }
        }

        private async Task InsertBulkCopyAsync<T>(IEnumerable<T> entities, CancellationToken cancellationToken) where T : class
        {
            var tableName = _queryCache.GetTableName<T>();
            var properties = GetInsertProperties<T>();
            var dataTable = _sqlBuilder.ToDataTable(entities, properties);
            var connection = (SqlConnection)await _connectionManager.GetOpenConnectionAsync().ConfigureAwait(false);
            var transaction = (SqlTransaction)_connectionManager.CurrentTransaction;
            using (var reader = dataTable.CreateDataReader())
            using (var bulkCopy = new SqlBulkCopy(connection, SqlBulkCopyOptions.Default, transaction))
            {
                ConfigureBulkCopy<T>(bulkCopy, dataTable, properties);
                await bulkCopy.WriteToServerAsync(reader, cancellationToken).ConfigureAwait(false);
            }
        }

        private void ConfigureBulkCopy<T>(SqlBulkCopy bulkCopy, DataTable dataTable, IEnumerable<PropertyInfo> properties) where T : class
        {
            var propertyList = properties as IList<PropertyInfo> ?? properties.ToList();
            bulkCopy.DestinationTableName = _queryCache.GetTableName<T>();
            bulkCopy.BatchSize = DEFAULT_BATCH_SIZE;
            bulkCopy.BulkCopyTimeout = _connectionManager.CommandTimeout;
            foreach (DataColumn column in dataTable.Columns)
            {
                var property = propertyList.FirstOrDefault(p =>
                {
                    var dbColumnName = _queryCache.GetColumnName(p).Trim('[', ']');
                    return dbColumnName == column.ColumnName;
                });
                if (property != null)
                    bulkCopy.ColumnMappings.Add(column.ColumnName, _queryCache.GetColumnName(property).Trim('[', ']'));
            }
        }

        private int InsertListWithIdentity<T>(IList<T> entities) where T : class
        {
            var identities = InsertBulkCopyWithIdentity(entities);
            var identityProp = _queryCache.GetIdentityProperty<T>();
            if (identityProp != null && identityProp.CanWrite)
            {
                SetIdentityValues(entities, identities, identityProp);
            }
            return entities.Count;
        }

        private async Task<int> InsertListWithIdentityAsync<T>(IList<T> entities, CancellationToken cancellationToken) where T : class
        {
            var identities = await InsertBulkCopyWithIdentityAsync(entities, cancellationToken).ConfigureAwait(false);
            var identityProp = _queryCache.GetIdentityProperty<T>();
            if (identityProp != null && identityProp.CanWrite)
            {
                SetIdentityValues(entities, identities, identityProp);
            }
            return entities.Count;
        }

        private static void SetIdentityValues<T>(IList<T> entities, List<object> identities, PropertyInfo identityProp) where T : class
        {
            for (int i = 0; i < entities.Count && i < identities.Count; i++)
            {
                try
                {
                    object convertedValue = Convert.ChangeType(identities[i], identityProp.PropertyType);
                    identityProp.SetValue(entities[i], convertedValue);
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException(
                        $"Failed to set identity value for entity at index {i}. " +
                        $"Identity value: {identities[i]}, Target type: {identityProp.PropertyType}", ex);
                }
            }
        }

        private List<object> InsertBulkCopyWithIdentity<T>(IEnumerable<T> entities) where T : class
        {
            var tempTableName = $"#Temp_{Guid.NewGuid():N}";
            var identities = new List<object>();
            var connection = (SqlConnection)_connectionManager.GetOpenConnection();
            try
            {
                CreateTempTableWithOrderColumn<T>(tempTableName, connection);
                BulkCopyToTempTableWithOrder<T>(entities, tempTableName, connection);
                identities = InsertFromTempAndRetrieveIdentitiesWithOrder<T>(tempTableName, connection);
            }
            finally { DropTempTable(tempTableName, connection); }
            return identities;
        }

        private async Task<List<object>> InsertBulkCopyWithIdentityAsync<T>(IEnumerable<T> entities, CancellationToken cancellationToken) where T : class
        {
            var tempTableName = $"#Temp_{Guid.NewGuid():N}";
            var identities = new List<object>();
            var connection = (SqlConnection)await _connectionManager.GetOpenConnectionAsync().ConfigureAwait(false);
            try
            {
                await CreateTempTableWithOrderColumnAsync<T>(tempTableName, connection, cancellationToken).ConfigureAwait(false);
                await BulkCopyToTempTableWithOrderAsync<T>(entities, tempTableName, connection, cancellationToken).ConfigureAwait(false);
                identities = await InsertFromTempAndRetrieveIdentitiesWithOrderAsync<T>(tempTableName, connection, cancellationToken).ConfigureAwait(false);
            }
            finally { await DropTempTableAsync(tempTableName, connection, cancellationToken).ConfigureAwait(false); }
            return identities;
        }

        private void CreateTempTableWithOrderColumn<T>(string tempTableName, SqlConnection connection)
        {
            var properties = GetInsertProperties<T>();
            var columns = string.Join(", ", properties.Select(p => _queryCache.GetColumnName(p)));
            var createTempTableQuery = $"SELECT TOP 0 {columns}, 0 AS [TempOrder] INTO {tempTableName} FROM {_queryCache.GetTableName<T>()};";
            _sqlBuilder.ExecuteRawCommand(connection, _connectionManager.CurrentTransaction, createTempTableQuery);
        }

        private async Task CreateTempTableWithOrderColumnAsync<T>(string tempTableName, SqlConnection connection, CancellationToken cancellationToken)
        {
            var properties = GetInsertProperties<T>();
            var columns = string.Join(", ", properties.Select(p => _queryCache.GetColumnName(p)));
            var createTempTableQuery = $"SELECT TOP 0 {columns}, 0 AS [TempOrder] INTO {tempTableName} FROM {_queryCache.GetTableName<T>()};";
            await connection.ExecuteAsync(new CommandDefinition(createTempTableQuery,
                transaction: _connectionManager.CurrentTransaction,
                cancellationToken: cancellationToken)).ConfigureAwait(false);
        }

        private void BulkCopyToTempTableWithOrder<T>(IEnumerable<T> entities, string tempTableName, SqlConnection connection)
        {
            var properties = GetInsertProperties<T>();
            var propertyList = properties as IList<PropertyInfo> ?? properties.ToList();
            var dataTable = _sqlBuilder.ToDataTable(entities, propertyList);
            dataTable.Columns.Add("TempOrder", typeof(int));
            for (int i = 0; i < dataTable.Rows.Count; i++) dataTable.Rows[i]["TempOrder"] = i;
            using (var reader = dataTable.CreateDataReader())
            using (var bulkCopy = new SqlBulkCopy(connection, SqlBulkCopyOptions.Default, (SqlTransaction)_connectionManager.CurrentTransaction))
            {
                bulkCopy.DestinationTableName = tempTableName;
                bulkCopy.BatchSize = DEFAULT_BATCH_SIZE;
                bulkCopy.BulkCopyTimeout = _connectionManager.CommandTimeout;
                foreach (DataColumn column in dataTable.Columns)
                {
                    var property = propertyList.FirstOrDefault(p =>
                    {
                        var dbColumnName = _queryCache.GetColumnName(p).Trim('[', ']');
                        return dbColumnName == column.ColumnName;
                    });
                    if (property != null)
                        bulkCopy.ColumnMappings.Add(column.ColumnName, _queryCache.GetColumnName(property).Trim('[', ']'));
                    else if (column.ColumnName == "TempOrder")
                        bulkCopy.ColumnMappings.Add(column.ColumnName, "TempOrder");
                }
                bulkCopy.WriteToServer(reader);
            }
        }

        private async Task BulkCopyToTempTableWithOrderAsync<T>(IEnumerable<T> entities, string tempTableName, SqlConnection connection, CancellationToken cancellationToken)
        {
            var properties = GetInsertProperties<T>();
            var propertyList = properties as IList<PropertyInfo> ?? properties.ToList();
            var dataTable = _sqlBuilder.ToDataTable(entities, propertyList);
            dataTable.Columns.Add("TempOrder", typeof(int));
            for (int i = 0; i < dataTable.Rows.Count; i++) dataTable.Rows[i]["TempOrder"] = i;
            using (var reader = dataTable.CreateDataReader())
            using (var bulkCopy = new SqlBulkCopy(connection, SqlBulkCopyOptions.Default, (SqlTransaction)_connectionManager.CurrentTransaction))
            {
                bulkCopy.DestinationTableName = tempTableName;
                bulkCopy.BatchSize = DEFAULT_BATCH_SIZE;
                bulkCopy.BulkCopyTimeout = _connectionManager.CommandTimeout;
                foreach (DataColumn column in dataTable.Columns)
                {
                    var property = propertyList.FirstOrDefault(p =>
                    {
                        var dbColumnName = _queryCache.GetColumnName(p).Trim('[', ']');
                        return dbColumnName == column.ColumnName;
                    });
                    if (property != null)
                        bulkCopy.ColumnMappings.Add(column.ColumnName, _queryCache.GetColumnName(property).Trim('[', ']'));
                    else if (column.ColumnName == "TempOrder")
                        bulkCopy.ColumnMappings.Add(column.ColumnName, "TempOrder");
                }
                await bulkCopy.WriteToServerAsync(reader, cancellationToken).ConfigureAwait(false);
            }
        }

        /// <summary>
        /// Inserts rows from the temp table into the real table, capturing generated identity
        /// values via OUTPUT INSERTED. The output temp table uses BIGINT for the Id column which
        /// is wide enough to receive INT, BIGINT, SMALLINT, TINYINT and DECIMAL-based identity
        /// columns. For GUID/uniqueidentifier identities this strategy is not supported and the
        /// caller should use the single-row Insert/InsertAsync methods instead.
        /// </summary>
        private List<object> InsertFromTempAndRetrieveIdentitiesWithOrder<T>(string tempTableName, SqlConnection connection) where T : class
        {
            var identityProp = _queryCache.GetIdentityProperty<T>();
            var properties = GetInsertProperties<T>();
            var tableName = _queryCache.GetTableName<T>();
            var identityColumnName = _queryCache.GetColumnName(identityProp).Trim('[', ']');
            var columnList = string.Join(", ", properties.Select(p => _queryCache.GetColumnName(p)));

            var insertQuery = $@"
        CREATE TABLE #OutputIds (TempOrder INT, Id BIGINT);
        INSERT INTO {tableName} ({columnList}) OUTPUT INSERTED.{identityColumnName} INTO #OutputIds(Id)
        SELECT {columnList} FROM {tempTableName} ORDER BY TempOrder;
        SELECT Id FROM #OutputIds ORDER BY TempOrder;
        DROP TABLE #OutputIds;";

            var identities = new List<object>();
            using (var command = new SqlCommand(insertQuery, connection, (SqlTransaction)_connectionManager.CurrentTransaction))
            using (var reader = command.ExecuteReader())
            {
                while (reader.Read()) identities.Add(reader.GetValue(0));
            }
            return identities;
        }

        private async Task<List<object>> InsertFromTempAndRetrieveIdentitiesWithOrderAsync<T>(string tempTableName, SqlConnection connection, CancellationToken cancellationToken) where T : class
        {
            var identityProp = _queryCache.GetIdentityProperty<T>();
            var properties = GetInsertProperties<T>();
            var tableName = _queryCache.GetTableName<T>();
            var identityColumnName = _queryCache.GetColumnName(identityProp).Trim('[', ']');
            var columnList = string.Join(", ", properties.Select(p => _queryCache.GetColumnName(p)));

            var insertQuery = $@"
        CREATE TABLE #OutputIds (TempOrder INT, Id BIGINT);
        INSERT INTO {tableName} ({columnList}) OUTPUT INSERTED.{identityColumnName} INTO #OutputIds(Id)
        SELECT {columnList} FROM {tempTableName} ORDER BY TempOrder;
        SELECT Id FROM #OutputIds ORDER BY TempOrder;
        DROP TABLE #OutputIds;";

            var identities = new List<object>();
            using (var command = new SqlCommand(insertQuery, connection, (SqlTransaction)_connectionManager.CurrentTransaction))
            using (var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false))
            {
                while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
                    identities.Add(reader.GetValue(0));
            }
            return identities;
        }

        private void DropTempTable(string tempTableName, SqlConnection connection)
        {
            try { _sqlBuilder.ExecuteRawCommand(connection, _connectionManager.CurrentTransaction, $"DROP TABLE {tempTableName}"); }
            catch { /* Ignore */ }
        }

        private async Task DropTempTableAsync(string tempTableName, SqlConnection connection, CancellationToken cancellationToken)
        {
            try
            {
                await connection.ExecuteAsync(new CommandDefinition($"DROP TABLE {tempTableName}",
                    transaction: _connectionManager.CurrentTransaction,
                    cancellationToken: cancellationToken)).ConfigureAwait(false);
            }
            catch { /* Ignore */ }
        }

        private IEnumerable<PropertyInfo> GetInsertProperties<T>() =>
            typeof(T).GetProperties().Where(p => p.GetCustomAttribute<IdentityAttribute>(true) == null);
    }
}
